/*
 version 3.5.160
*/
'use strict';var tns_already,tnscm_adn=tnscm_adn||[];window.tnscm_pak="";window.cm_events=window.cm_events||[];
(function(){var r,u;r=function(){function s(){}function g(a,c){var b,d;if(a&&(d=a.length))for(b=0;b<d;b+=1)try{c(a[b],b,a)}catch(e){}}function k(a,c){for(var b=0,d=a.length;b<d;)if(a[b++]===c)return b-1;return-1}function r(a,c){return function(){return a.apply(c,arguments)}}function q(a,c,b){window.addEventListener?a.addEventListener(c,b,!1):window.attachEvent&&a.attachEvent("on"+c,b)}function n(a){function c(){g(n.a,function(a){a()});delete n.a}function b(){"loading"!==document.readyState&&(c(),
document.detachEvent("onreadystatechange",b))}"loading"!==document.readyState?a():n.a?n.a.push(a):(n.a=[a],document.addEventListener?document.addEventListener("DOMContentLoaded",c,!1):document.attachEvent&&document.attachEvent("onreadystatechange",b))}function f(a){function c(){for(f.time=w&&0<w.loadEventStart?new Date(w.loadEventStart):new Date;b.length;)b.shift()(f.time)}var b;f.time?a(f.time):(f.e||(f.e=[],q(window,"load",c)),b=f.e,b.push(a),"complete"===document.readyState&&c())}function p(a){var c=
{};a&&g(a.split("&"),function(a){a=a.split("=");c[decodeURIComponent(a[0].toLowerCase())]=decodeURIComponent(a[1])});return c}function m(){var a=document.body,c=document.documentElement,a=a?Math.max(a.scrollHeight,a.offsetHeight,a.clientHeight):0;return Math.max(a,c.scrollHeight,c.offsetHeight,c.clientHeight)}function h(a,c){var b;return document.defaultView&&document.defaultView.getComputedStyle?(c=c.replace(/([A-Z])/g,"-$1").toLowerCase(),(b=document.defaultView.getComputedStyle(a,null))&&b.getPropertyValue(c)):
a.currentStyle?a.currentStyle[c]:a.style&&a.style[c]?a.style[c]:null}function l(a){if(!a)return{top:0,left:0};var c={top:a.offsetTop,left:a.offsetLeft};a=l(a.offsetParent);c.top+=a.top;c.left+=a.left;isNaN(c.top)&&(c.top=void 0);isNaN(c.left)&&(c.left=void 0);return c}function y(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document||null}function z(a,c){for(var b=a.childNodes,d=b.length,e;d--;)if(e=z(b[d],c))return e;return c(a)}var x=["","moz","ms","webkit"],v=window.performance,
w=v?v.timing:null,v=function(){if("undefined"==typeof navigator.plugins||0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}();return{w:s,random:function(){var a=(new Date).valueOf().toString();return parseInt(a.substr(a.length-8,a.length))+Math.round(Math.random()*Math.pow(10,9))},s:v,trim:function(a){return void 0!==String.prototype.trim?String.prototype.trim.call(a):a.replace(/^\s+|\s+$/g,
"")},b:g,indexOf:k,v:function(a,c,b){var d,e;b=b||s;if(!a)return!1;e=a.length;0===e&&b();if(e)return d=setInterval(function(){var g=10;do{e-=1;if(-1===e){clearInterval(d);b();break}c(a[e],e,a)}while(--g)},4)},extend:function(a,c,b){var d,e;for(d in c)c.hasOwnProperty(d)&&(e=c[d],a[d]=b&&"function"===typeof e?r(e,a):e)},on:q,C:n,load:f,A:function(a){q(window,"scroll",a);q(window,"resize",a);a()},B:function(a,c){function b(){var b=document[e]||"visible";switch(b){case "hidden":c(b);break;default:a(b)}}
var d,e;c=c||s;for(d=0;d<x.length;d++)if(e=x[d]+"VisibilityState",e=e.charAt(0).toLowerCase()+e.substring(1),document[e]){q(document,x[d]+"visibilitychange",b);"hidden"!==document[e]&&b();return}b()},g:p,i:function(a){function c(a){var b=!1;g(["link1","clicktag","alink1","url","adress"],function(c){a.hasOwnProperty(c)&&(b=a[c])});return b}var b,d,e=a.childNodes,t=a.parentNode,h="",f={};switch(a.nodeName){case "IMG":for(;t;){if("A"===t.nodeName){b=t.href;break}t=t.parentNode}break;case "OBJECT":g(e,
function(a){"PARAM"===a.nodeName&&"flashvars"===a.getAttribute("name").toLowerCase()&&(d=a.getAttribute("value"),f=p(d.replace(/&amp;/g,"&")),b=c(f))});break;case "EMBED":if(h=a.getAttribute("flashvars"))f=p(h.replace(/&amp;/g,"&")),b=c(f)}try{"string"===typeof b&&(b=decodeURIComponent(b))}catch(m){}return b},k:m,u:function(a){for(var c=!1,b=a.getClientRects(),d=m(),e=b.length;e--;)if(a=b[e],0!==a.width&&0!==a.height){if(0<a.top)return a.top<=d;if(0<a.bottom)return a.bottom<=d;c=!0}return c},q:h,
n:l,p:function(a){var c={d:["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],c:["paddingTop","paddingBottom","borderTopWidth","borderBottomWidth"]},b,d,e;"svg"==a.nodeName?(b=a.getBoundingClientRect(),b={d:Math.round(b.width),c:Math.round(b.height)}):b={d:a.offsetWidth,c:a.offsetHeight};for(d in b)if(b.hasOwnProperty(d)){if(0<b[d])for(e=c[d].length;e--;)b[d]-=parseInt(h(a,c[d][e]),10)||0;e=b[d]||h(a,"w"===d?"width":"height");/%/.test(e)||(b[d]=parseInt(e,10),isNaN(b[d])&&(b[d]=0))}return b},
j:y,r:function(){var a=document.body,c=document.documentElement;return"number"===typeof window.pageYOffset?window.pageYOffset:c&&c.scrollTop?c.scrollTop:a&&a.scrollTop?a.scrollTop:0},f:z,t:function(a){try{var c=a.getAttribute("src")||"",b=c.indexOf("//"+location.host),d;if((0!==c.indexOf("http")&&0!==c.indexOf("//")||-1<b&&8>b)&&(d=y(a))&&d.getElementById)return!0}catch(e){}return!1},m:function(a){function c(a){-1===k(excludeElements,a)&&excludeElements.push(a)}function b(a){var b=document.createElement("a");
b.href=a;return b.href}var d,e,f;if(!a.tagName)return!1;if("OBJECT"===a.tagName){d=a.getAttribute("data");a=a.childNodes;if(!d)for(e=a.length;e--;)if(f=a[e],"PARAM"===f.nodeName&&"movie"===f.getAttribute("name").toLowerCase())return f.getAttribute("value");for(e=a.length;e--;)if(f=a[e],"PARAM"===f.nodeName&&"flashvars"===f.getAttribute("name").toLowerCase()&&(f=p(f.getAttribute("value").replace(/&amp;/g,"&")),f.video1))try{return decodeURIComponent(f.video1)}catch(h){return f.video1}return d}if("VIDEO"===
a.tagName){d=a.childNodes;f=d.length;var m,l;if(!a.canPlayType)return!1;for(e=0;e<f;e++)if(m=d[e],"SOURCE"===m.nodeName&&(l=m.getAttribute("type"),a.canPlayType(l)))return d=m.getAttribute("src")||!1,g(a.getElementsByTagName("embed"),c),g(a.getElementsByTagName("object"),c),d;return d=a.getAttribute("src")}if("SVG"===a.tagName.toUpperCase())e=a.getElementsByTagName("image"),0<e.length&&(d=e[0].getAttribute("xlink:href"));else{e=(d=a.getAttribute("src"))&&"data:image"==d.substring(0,10);f=d&&(0==d.indexOf("//")||
0==d.indexOf("http"));if(null==d||e)return d&&e?u.juke_host[0]||null:null;d=a.getAttribute("src");f||(d=b(d))}return d},l:function(a){var c,b;if(top!=self&&window.addonCMeter&&window.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.offset){b=window;c=document;var d=c.documentElement,e=c.getElementsByTagName("body")[0];c=b.innerWidth||d.clientWidth||e.clientWidth;b=b.innerHeight||d.clientHeight||e.clientHeight;return 10>=Math.abs(c-a.d)&&10>=Math.abs(b-a.c)?addonCMeter.currentValues.offset:
0}return 0},o:function(){var a=u;return window.addonCMeter&&addonCMeter.config&&addonCMeter.config.region||a.region||"ua"}}}();u=function(s){var g={source:"source.mmi.bemobile.ua",juke_host:["pa.tns-ua.com/bug/pic.gif"],host:"pagestat.mmi.bemobile.ua",sslhost:"sslpagestat.mmi.bemobile.ua",err_host:"er.mmi.bemobile.ua",timer:{frequency:5,pings:[5,15,30,60,120],stop_after:5},ads:{scan_frequency:5,width:50,height:40},video:{url:"vplayer.mmi.bemobile.ua/vplayer/html5"}};s.extend(g,window.addonCMeter&&
addonCMeter.config);g.custom_url&&location.host===g.custom_url.href?(g.ads.scan_frequency=g.custom_url.banner_scan_frequency,g.work_in_frame=g.custom_url.work_in_frame):g.work_in_frame=!0;"string"===typeof g.juke_host&&(g.juke_host=[g.juke_host]);return g}(r);(function(s,g){function k(f){function m(){g.b(k.a,function(f){f()});delete k.a}function h(){"loading"!==document.readyState&&(m(),document.detachEvent("onreadystatechange",h))}"loading"!==document.readyState?f():k.a?k.a.push(f):(k.a=[f],document.addEventListener?
document.addEventListener("DOMContentLoaded",m,!1):document.attachEvent&&document.attachEvent("onreadystatechange",h))}function r(f,m){function h(f){l.onload=l.onerror=l.onreadystatechange=null;m(f)}var l=document.createElement("script"),k=document.getElementsByTagName("script"),n=k.length;g.extend(l,{async:!0,type:"text/javascript",onload:function(){h(null)},onerror:h,onreadystatechange:function(){"loaded"!==l.readyState&&"complete"!==l.readyState||h(null)}});l.src=f;k[n-1].parentNode.insertBefore(l,
k[n-1].nextSibling)}var q=/cmeter_an\.js(#(.+))?/,n={add:function(f){tnscm_adn=tnscm_adn||[];0>g.indexOf(tnscm_adn,f)&&tnscm_adn.push(f)}},f;g.b(document.getElementsByTagName("script"),function(p){p=p.getAttribute("src");q.test(p)&&(p=q.exec(p)[2])&&(f=g.g(p),f.tnscm_adn&&k(function(){(0<=g.indexOf(tnscm_adn,"inline_cm")||g.f(document,function(f){if(8===f.nodeType&&"MMI CMeter"===g.trim(f.nodeValue))return!0}))&&n.add("inline_cm");n.add(f.tnscm_adn)}),f.tnscm_pak&&(window.tnscm_pak=f.tnscm_pak))});
k(function(){function k(){g.b(["uid","fp"],function(g){f.hasOwnProperty(g)&&window.cm_events.push({event:"send",callback:function(h){h&&"~cm_banners~"==h.param1&&(h[g]=f[g]);return h}})})}tns_already?k():(tns_already=1,r(("https:"==location.protocol?"https:":"http:")+"//"+s.source+"/cm/cm.js",function(g){g||(f.hasOwnProperty("no_referrer")&&window.cm_events.push({event:"send",h:function(f){delete f.referrer;return f}}),k())}))})})(u,r)})();
